=== Javier-Coronel/Lenguaje-de-marcas/U1/U1_T2_DTD/discografica_ext.dtd
<!ELEMENT discografica (disco)*>
<!ELEMENT disco (titulo, interpretes, numeroDePistas,pistas)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT interpretes (interprete)+>
<!ELEMENT interprete (nombre,apellidos,rol?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT numeroDePistas (#PCDATA)>
<!ELEMENT pistas (pista+)>
<!ELEMENT pista (nombre,duracion)>
<!ELEMENT duracion (#PCDATA)>

=== Javier-Coronel/Lenguaje-de-marcas/U1/U1_T2_DTD/discografica_ext.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE discografica SYSTEM "discografica_ext.dtd">
<discografica>
    <disco>
        <titulo></titulo>
        <interpretes>
            <interprete>
                <nombre></nombre>
                <apellidos></apellidos>
            </interprete>
        </interpretes>
        <numeroDePistas></numeroDePistas>
        <pistas>
            <pista>
                <nombre></nombre>
                <duracion></duracion>
            </pista>
        </pistas>
    </disco>
</discografica>
